[package]
name = "drivers"
version = "0.1.0"
authors = ["noname"]
edition = "2021"

[dependencies]
kernel = { path = "../../tock/kernel" }
enum_primitive = { path = "../../tock/libraries/enum_primitive" }
tickv = { path = "../../tock/libraries/tickv" }

